# CONFIG FILE SIMPLE-RENAME
#
#Language (en , es, eu, custom)
#METRICS: Enable or Disable Metrics
#UPDATER: Enable or Disable the update notifier
#ECONOMY:(If you set it to "true" yo need to have Vault installed)
#PRICES: Price to rename and relore items 
Language: en
Metrics: true
Updater: true
#ECONOMY (VAULT NEEDED)
Economy: false
Nprice: 10 
Lprice: 10

#THIS CONFIG FILE WAS CREATED BY SIMPLE-RENAME (v2.5)
