# CONFIG FILE SIMPLE-RENAME
# THIS CONFIG FILE WAS CREATED BY SIMPLE-RENAME (v5.0)
#Language (en , es, eu, nl, fr, custom)
Language: en
#METRICS: Enable or Disable Metrics
Metrics: true
#UPDATER: Enable or Disable the update notifier
Updater: true
#ECONOMY:(If you set it to "true" yo need to have Vault installed)
Economy: false
#PRICES: Price to rename and relore items 
Nprice: 10 
Lprice: 10
#Blacklisted words
BlackList:
  - blaclistedwords
#Blaclisted items / blocks. Use names, NOT IDs 
BlackListID:
  - air


