name: SimpleRename
main: io.github.galaipa.sr.Main
version: 1.0
author: Galaipa
description: Simple plugin to rename and relore items
softdepend: [Vault]

commands:
  rename:
    description: Name command for items
    usage: /<command>  
    aliases: [setname]
  relore:
    description: Lore command for items
    usage: /<command> 
    aliases: [setlore]
  sr:
    description: Command to update the plugin
    usage: /<command>    
permissions:
  sr.name:
    description: Perm to use /rename /setname
    default: op
  sr.lore:
    description: Perm to use /relore /setlore
    default: op
  sr.color:
    description: Perm to use color codes
    default: op
  sr.free:
    description: Perm to use the commands for free
    default: false
  sr.update:
    description: Perm to use the /sr update
    default: op